name: Build BLE-Daikin N16R8

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:v5.4

    steps:
      - uses: actions/checkout@v4

      - name: Build
        shell: bash
        run: |
          . /opt/esp/idf/export.sh
          cd ESP
          idf.py build

      - name: Prepare output
        run: |
          cd ESP/build
          esptool.py --chip esp32s3 merge_bin --output BLE-Daikin-N16R8.bin \
            0x0 bootloader/bootloader.bin \
            0x8000 partition_table/partition-table.bin \
            0x10000 BLE-Daikin.bin

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: BLE-Daikin-N16R8
          path: ESP/build/BLE-Daikin-N16R8.bin
